"""empty message

Revision ID: 6c83fe7848ba
Revises: 
Create Date: 2025-09-04 21:56:07.883181

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c83fe7848ba'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('study',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('study_code', sa.String(length=20), nullable=False),
    sa.Column('health_program', sa.String(length=50), nullable=False),
    sa.Column('protocol_num', sa.String(length=50), nullable=False),
    sa.Column('protocol_desc', sa.String(length=200), nullable=False),
    sa.Column('project_num', sa.String(length=20), nullable=False),
    sa.Column('ctgov_num', sa.String(length=20), nullable=True),
    sa.Column('research_type', sa.String(length=50), nullable=True),
    sa.Column('study_design', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('protocol_num'),
    sa.UniqueConstraint('study_code'),
    sa.UniqueConstraint('study_code', name='uq_study_study_code')
    )
    op.create_table('data_col_method',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('study_id', sa.String(), nullable=False),
    sa.Column('data_collection_tool', sa.String(length=50), nullable=True),
    sa.Column('data_collection_tool_other', sa.String(length=50), nullable=True),
    sa.Column('randomization', sa.String(length=50), nullable=True),
    sa.Column('use_tablets', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['study_id'], ['study.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('other_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('study_id', sa.String(), nullable=False),
    sa.Column('find_role', sa.String(length=50), nullable=True),
    sa.Column('study_population', sa.String(length=50), nullable=True),
    sa.Column('investigational_status', sa.String(length=50), nullable=True),
    sa.Column('oir_team', sa.String(length=50), nullable=True),
    sa.Column('additional_notes', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['study_id'], ['study.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('study_site',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_code', sa.String(length=20), nullable=False),
    sa.Column('study_id', sa.String(), nullable=False),
    sa.Column('site_name', sa.String(length=50), nullable=False),
    sa.Column('site_country_id', sa.String(length=50), nullable=True),
    sa.Column('site_city', sa.String(length=200), nullable=True),
    sa.Column('site_sample_size', sa.Integer(), nullable=True),
    sa.Column('site_pi_name', sa.String(length=20), nullable=True),
    sa.Column('site_pi_gender', sa.String(length=50), nullable=True),
    sa.Column('pi_location', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['study_id'], ['study.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('site_code')
    )
    op.create_table('study_timeline',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('study_id', sa.String(), nullable=False),
    sa.Column('estimated_fpfv', sa.DateTime(), nullable=True),
    sa.Column('estimated_lplv', sa.DateTime(), nullable=True),
    sa.Column('actual_fpfv', sa.DateTime(), nullable=True),
    sa.Column('actual_lplv', sa.DateTime(), nullable=True),
    sa.Column('active_years', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['study_id'], ['study.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('team_member',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('study_id', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(length=50), nullable=False),
    sa.Column('study_role', sa.String(length=50), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['study_id'], ['study.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('team_member')
    op.drop_table('study_timeline')
    op.drop_table('study_site')
    op.drop_table('other_details')
    op.drop_table('data_col_method')
    op.drop_table('study')
    # ### end Alembic commands ###
